
int bitXor(int, int);
int test_bitXor(int, int);
int allOddBits();
int test_allOddBits();
int getByte(int, int);
int test_getByte(int, int);
int reverseBytes(int);
int test_reverseBytes(int);
int bitMask(int, int);
int test_bitMask(int, int);
int bang(int);
int test_bang(int);
int isNegative(int);
int test_isNegative(int);
int negate(int);
int test_negate(int);
int subOK(int, int);
int test_subOK(int, int);
int isLess(int, int);
int test_isLess(int, int);
int multFiveEighths(int);
int test_multFiveEighths(int);
unsigned float_abs(unsigned);
unsigned test_float_abs(unsigned);
int float_f2i(unsigned);
int test_float_f2i(unsigned);
